name: Some workflow

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  whatever:
    runs-on: ubuntu-latest
    steps:
      - name: Ls before checkout
        run: find .
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ls after checkout
        run: find .
